### ISSUE TITLE
BUILD. Minha Aula de Excelência.

### ISSUE THREAD

**Issue by FA101** [Programa-k/Turma-II#8]
### Líder para a IDEIA:

Fillipe Mendonça Albuquerque

### Minha IDEIA é:

O ensino superior no INF, na UFG e no Brasil como um todo sofre com o famoso "fazejamento", ou seja, muitos docentes não planejam as aulas, não debatem os métodos, não recebem feedbacks e mantém um loop de fracassos, reprovações e fingimentos semestre após semestre.

### Nossa SOLUÇÃO é:

Desenvolver uma aplicação web, responsiva e multiplataforma, que auxilie o docente no planejamento estruturado do ensino, ofereça uma rede de apoio previamente mapeada e possua uma ferramenta de feedback anônimo dos discentes.

### Nossa HISTÓRIA (fatos marcantes - milestones):

@FA101 @tperaro @GabrielCCastrodev @kevengond @Thiago-V-A @LeonardoRibeirOliveira @phablo-tavares @MauricioMoraesP 

### Checklist de uma IDEIA - QUADRO IDEAÇÃO:

- [X] 0- Empatia: acho que captei os desejos e ou as dores de alguém ... (INSPIRAÇÃO)
- [X] 1- Descrição do PROBLEMA: acho que consigo explicar o PROBLEMA de forma clara para outras pessoas (Minha IDEIA) ...
- [ ] 3- Temos uma SOLUÇÃO escolhida e de certa forma planejada (sonhada!), e está descrita em Nossa SOLUÇÃO ...
- [ ] 2- Temos um GRUPO: o Grupo não é grande demais e nem pequeno demais (e depende da próxima ETAPA! Rsss...)
- [ ] 4- Nossa SOLUÇÃO escolhida, está em votação...
- [ ] 5- Dada a nossa SOLUÇÃO, o próximo STAGE está claro (bem planejado!), e descrito sucintamente em Nossa HISTÓRIA ...
- [ ] 6- Agendamos com um(a) Tutor(a)...
- [ ] 7- Temos uma DECISÃO que foi registrada com a DATA e o parecer do(a) Tutor(a)... em Nossa HISTÓRIA ...

### Checklist de uma IDEIA - QUADRO IMPLEMENTAÇÃO:

- [ ] 8- Executando o STAGE aprovado!
- [] 9- Finalizamos o STAGE e estamos agendando com um(a) Tutor(a)...
- [ ] 10- Temos uma DECISÃO que foi registrada com a DATA e o parecer do(a) Tutor(a)... em Nossa HISTÓRIA ...

**Comment by FA101** [comment]
Até o momento...

- Foi criado um grupo de WhatsApp com os oito integrantes do projeto. 
- Foi realizada uma apresentação preliminar do escopo, com divisão de três módulos principais: planejamento estruturado do ensino, rede de apoio docente e feedback.
- Foi sugerida opções de datas e horários da primeira reunião para discussão das atividades, datas e stages para votação.

**Comment by FA101** [comment]
**STAGE 1** 
**[INSTRUCTION]**
*Duração: 10 dias úteis*

As atividades são listadas para cada módulo da aplicação que são: Ensino, Feedback e Gestão.

**Atividades de Ensino:** 
1. Pesquisar sobre CRUD do PPC, Plano de Ensino, RGCG, resoluções da unidade acadêmica e leis de proteção e apoio ao estudante;
2. Pesquisar tipos de aula (invertida, tradicional, prática, seminário etc), didáticas de ensino superior e estruturas típicas;
3. Entrevistar docentes e discentes sobre experiências de excelência no ensino;
4. Pesquisar conteúdos de ensino em plataformas gratuitas com maior número de visualizações e maior número de assinantes, e avaliar métodos utilizados.

**Atividades de Feedback**
5. Pesquisar sistemas de recomendação, feedback e avaliação modernos, com foco em objetividade, engajamento das partes envolvidas e eficácia;
6. Pesquisar métodos de autoavaliação, avaliação cruzada (discentes x docentes) e simplificação para uso por aula;
7. Pesquisar modos de feedback da rede de apoio, alunos, coordenadores e diretores sobre conteúdo da aula;
8. Pesquisar sobre modo de funcionamento da rede de apoio a respeito da estrutura da aula, método de pull request e download de conteúdos assessorados.

**Atividades de Gestão**
9. Pesquisar quadro de divulgação de impacto, eficiência e eficácia para docentes e disciplinas;
10. Pesquisar sobre gameficação para a aplicação e partes envolvidas;
11. Pesquisar sobre potenciais aplicação de IA nos módulos;
12. Pesquisar meios de facilitar CRUD para disciplinas, docentes, discentes e rede de apoio.

**Atividades do Líder**
13. Orientar equipe, avaliar e revisar resultados das pesquisas;
14. Registrar resultados aderentes em relatório e monitorar os prazos;
15. Definir avanço do STAGE com tutor e com equipe;
16. Definir atividades do próximo STAGE.

**Comment by FA101** [comment]
Em votação este projeto alcançou 41 votos. Já foi enviado convite para reunião com tutor.

**Comment by FA101** [comment]
Houve tentativa de reunião com tutor hoje, porém sem sucesso. 
Uma nova agenda foi marcada para amanhã, dia 29/02/2024 com um novo tutor.

**Comment by FA101** [comment]
No dia 29/02/2024 houve reunião com a tutora Luciana e o Federson. A equipe sofreu um AGAIN. As observações de melhoria foram:

1. Reduzir o escopo para o próximo GATE
2. Esclarecer os objetivos de cada atividade da INSTRUCTION e sua relação com o próximo BUILD
3. Definir um planejamento dia a dia das atividades, com por quê e para quê delas
4. Quebrar as atividades tarefas, com recursos aplicados e entregas claras
5. Definir a meta de cada tarefa com os resultados esperados para ela
6. Incluir nas atividades o nivelamento da equipe sobre o assunto do projeto
7. Utilizar checklists para verificar o avanço das tarefas
8. Fazer uma apresentação visual para o próximo stage-gate

**Comment by FA101** [comment]
No dia 01/03/2024 houve reunião sobre o AGAIN. Cada membro da equipe ficou responsável por fazer uma reflexão a respeito dos comentários dos tutores a respeito do projeto. A reflexão serviu como combustível para a definição dos próximos passos.

No dia 05/03/2024 houve reunião sobre o novo STAGE-GATE. Uma apresentação começou a ser elaborada, com divisão de assuntos tratados por cada um e debate sobre o rumo que a equipe irá seguir.

No dia 07/03/2024 haverá uma reunião de fechamento da apresentação do novo STAGE-GATE. O produto dessa reunião é o alinhamento sobre como iremos para a apresentação com o tutor, e agendamento desse momento no DISCORD e no Google Meet. O agendamento possui um padrão que precisa ser obedecido e que foi comentado pelo Fernando Federson.

**Comment by FA101** [comment]
A equipe alcançou o GO hoje, tutor professor Fábio Lucena! 
Foi iniciada a elaboração da estrutura do relatório informacional para redação colaborativa, divisão dos recursos alocados por tema e características das entregas.

**Comment by FA101** [comment]
No dia 16/03/2024 tivemos uma reunião com o tutor Fábio Lucena. Foi apresentado um Relatório Informacional contendo as entregras indicadas no gate, de forma descritiva, em um documento de 56 páginas abordando: Escopo/Domínio, Requisitos, Arquitetura e Qualidade.

Em uma reunião de 2h a equipe recebeu um AGAIN, com o feedback de:
1) Dar um passo atrás e enxugar a entrega.
2) Caracterizar o produto a partir do Design Thinking, Lean e Agile. Ter uma visão clara do produto.

Um apresentação está em elaboração com as entregas enxutas do que foi apontado no GO. O agendamento do GATE deve ficar para a semana 12, entre 17/03/2024 a 23/03/2024.

**Comment by FA101** [comment]
Agendamento de GATE para dia 27/03/2024 às 18h com o tutor Fábio Lucena.
Inicialmente foi realizado um agendamento para segunda-feira, 25/03/2024, porém outro grupo já estava com essa janela preenchida com o tutor e por isso foi necessário o reagendamento.

**Comment by FA101** [comment]
Hoje, 27/03/2024, essa equipe alcançou um GLORY. 
Os artefatos gerados foram:
• Apresentação de stage
• Relatório Informacional
• Lista de Documentos
• Apresentação de resultados
Todos disponíveis na pasta: https://drive.google.com/drive/folders/1WxGICb_5jU75mz6XStYPjuT0gNCoxStK?usp=sharing
